nginx:
   build: ./nginx-filebeat
   ports:
    - "80:80"
   links:
    - elk
   volumes:
    - ./log/:/var/log/nginx
elk:
   build: .
   ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
   volumes:
    - ./log/:/var/log/nginx

